FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD Springboot.jar /opt/Springboot/
EXPOSE 8080
WORKDIR /opt/Springboot/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "Springboot.jar"]
